# basic info
name: StatefulWordCount

mode: cross-region
#mode: offline
# resource configuration
debug: true
local_operators:
  - "Source: Bids Source-1"
remote_operators:
  - "Mapper-2"
  - "Latency Sink-3"

local_parallelism: 1
remote_parallelism: 1
parallelism: 2