# basic info
name: StatefulWordCount

mode: cross-region
#mode: offline
# resource configuration
local_parallelism: 1
remote_parallelism: 3
local_slot_group: local_group
remote_slot_group: remote_group
#isDebug: true
# partition configuration

local_operators:
  - sentence-source
remote_operators:
  - flatmap
  - count
  - dummy-sink
